server {
    listen 80;

    # React sahifalarini ko'rsatish
    location / {
        root /usr/share/nginx/html;
        index index.html;
        if ($request_filename ~* \.apk$) {
            add_header Content-Type application/vnd.android.package-archive;
            add_header Content-Disposition 'attachment; filename="bpos.apk"';
        }
        try_files $uri $uri/ /index.html;
    }

    # API so'rovlarini Django-ga yuborish
    location /api/ {
        proxy_pass http://django_backend:8000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    # Django Admin paneli uchun
    location /admin/ {
        proxy_pass http://django_backend:8000;
        proxy_set_header Host $host;
    }

    # Django Static fayllari (rasmlar, stillar)
    location /static/ {
        proxy_pass http://django_backend:8000;
    }

    location /ws/ {
        proxy_pass http://django_backend:8000;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "Upgrade";
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}