server {
    listen 80;

    # React sahifalarini ko'rsatish
    location / {
        root /usr/share/nginx/html;
        index index.html;
        try_files $uri $uri/ /index.html;
    }

    # API so'rovlarini Django-ga yuborish
    location /api/ {
        proxy_pass http://django_backend:8000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    # Django Admin paneli uchun
    location /admin/ {
        proxy_pass http://django_backend:8000;
        proxy_set_header Host $host;
    }

    # Django Static fayllari (rasmlar, stillar)
    location /static/ {
        proxy_pass http://django_backend:8000;
    }
}